// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/topdata/cronjob/v1/cronjob.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// TopdataClient is the client API for Topdata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopdataClient interface {
}

type topdataClient struct {
	cc grpc.ClientConnInterface
}

func NewTopdataClient(cc grpc.ClientConnInterface) TopdataClient {
	return &topdataClient{cc}
}

// TopdataServer is the server API for Topdata service.
// All implementations must embed UnimplementedTopdataServer
// for forward compatibility
type TopdataServer interface {
	mustEmbedUnimplementedTopdataServer()
}

// UnimplementedTopdataServer must be embedded to have forward compatible implementations.
type UnimplementedTopdataServer struct {
}

func (UnimplementedTopdataServer) mustEmbedUnimplementedTopdataServer() {}

// UnsafeTopdataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopdataServer will
// result in compilation errors.
type UnsafeTopdataServer interface {
	mustEmbedUnimplementedTopdataServer()
}

func RegisterTopdataServer(s grpc.ServiceRegistrar, srv TopdataServer) {
	s.RegisterService(&Topdata_ServiceDesc, srv)
}

// Topdata_ServiceDesc is the grpc.ServiceDesc for Topdata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Topdata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.topdata.cronjob.v1.Topdata",
	HandlerType: (*TopdataServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/topdata/cronjob/v1/cronjob.proto",
}
