// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/topdata/service/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Topdata_List_FullMethodName = "/api.topdata.service.v1.Topdata/List"
)

// TopdataClient is the client API for Topdata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TopdataClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
}

type topdataClient struct {
	cc grpc.ClientConnInterface
}

func NewTopdataClient(cc grpc.ClientConnInterface) TopdataClient {
	return &topdataClient{cc}
}

func (c *topdataClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, Topdata_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopdataServer is the server API for Topdata service.
// All implementations must embed UnimplementedTopdataServer
// for forward compatibility
type TopdataServer interface {
	List(context.Context, *ListRequest) (*ListReply, error)
	mustEmbedUnimplementedTopdataServer()
}

// UnimplementedTopdataServer must be embedded to have forward compatible implementations.
type UnimplementedTopdataServer struct {
}

func (UnimplementedTopdataServer) List(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTopdataServer) mustEmbedUnimplementedTopdataServer() {}

// UnsafeTopdataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopdataServer will
// result in compilation errors.
type UnsafeTopdataServer interface {
	mustEmbedUnimplementedTopdataServer()
}

func RegisterTopdataServer(s grpc.ServiceRegistrar, srv TopdataServer) {
	s.RegisterService(&Topdata_ServiceDesc, srv)
}

func _Topdata_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopdataServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Topdata_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopdataServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Topdata_ServiceDesc is the grpc.ServiceDesc for Topdata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Topdata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.topdata.service.v1.Topdata",
	HandlerType: (*TopdataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Topdata_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/topdata/service/v1/service.proto",
}
