// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tophub/app/topdata/service/internal/biz"
	"tophub/app/topdata/service/internal/conf"
	"tophub/app/topdata/service/internal/data"
	"tophub/app/topdata/service/internal/server"
	"tophub/app/topdata/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	topdataRepo := data.NewTopdataRepo(dataData, logger)
	topdataUseCase := biz.NewTopdataUseCase(topdataRepo, logger)
	topdataService := service.NewTopDataService(topdataUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, topdataService, logger)
	httpServer := server.NewHTTPServer(confServer, topdataService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
