// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
	"tophub/app/job/internal/biz"
	"tophub/app/job/internal/conf"
	"tophub/app/job/internal/data"
	"tophub/app/job/internal/server"
	"tophub/app/job/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	consumer := data.NewKafkaConsumer(confData)
	dataData, cleanup, err := data.NewData(consumer, logger)
	if err != nil {
		return nil, nil, err
	}
	jobRepo := data.NewJobRepo(dataData, logger)
	jobUseCase := biz.NewJobUseCase(jobRepo, logger)
	jobService := service.NewJobService(jobUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, tracerProvider, jobService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
