// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTopdatum = "topdata"

// Topdatum mapped from table <topdata>
type Topdatum struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Tab        string    `gorm:"column:tab;type:varchar(32);not null" json:"tab"`                                         // 标识
	Position   int64     `gorm:"column:position;type:tinyint unsigned;not null" json:"position"`                          // 资讯位置
	Title      string    `gorm:"column:title;type:varchar(512);not null" json:"title"`                                    // 资讯标题
	URL        string    `gorm:"column:url;type:varchar(512);not null" json:"url"`                                        // 资讯地址
	Extra      string    `gorm:"column:extra;type:json;not null" json:"extra"`                                            // 拓展字段
	SpiderTime time.Time `gorm:"column:spider_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"spider_time"` // 抓取时间
}

// TableName Topdatum's table name
func (*Topdatum) TableName() string {
	return TableNameTopdatum
}
