// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFeed = "feed"

// Feed mapped from table <feed>
type Feed struct {
	ID int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName Feed's table name
func (*Feed) TableName() string {
	return TableNameFeed
}
