// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTophubFeed = "tophub_feed"

// TophubFeed mapped from table <tophub_feed>
type TophubFeed struct {
	ID int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName TophubFeed's table name
func (*TophubFeed) TableName() string {
	return TableNameTophubFeed
}
