// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tophub/app/topdata/cronjob/internal/conf"
	"tophub/app/topdata/cronjob/internal/data"
	"tophub/app/topdata/cronjob/internal/server"
	"tophub/app/topdata/cronjob/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	cron := service.NewCron(db)
	topdataService := service.NewTopDataService(cron, logger)
	grpcServer := server.NewGRPCServer(confServer, topdataService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
