// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zag13/tophub/server/dal/model"
)

func newFeed(db *gorm.DB, opts ...gen.DOOption) feed {
	_feed := feed{}

	_feed.feedDo.UseDB(db, opts...)
	_feed.feedDo.UseModel(&model.Feed{})

	tableName := _feed.feedDo.TableName()
	_feed.ALL = field.NewAsterisk(tableName)
	_feed.ID = field.NewInt64(tableName, "id")

	_feed.fillFieldMap()

	return _feed
}

type feed struct {
	feedDo feedDo

	ALL field.Asterisk
	ID  field.Int64

	fieldMap map[string]field.Expr
}

func (f feed) Table(newTableName string) *feed {
	f.feedDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f feed) As(alias string) *feed {
	f.feedDo.DO = *(f.feedDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *feed) updateTableName(table string) *feed {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")

	f.fillFieldMap()

	return f
}

func (f *feed) WithContext(ctx context.Context) *feedDo { return f.feedDo.WithContext(ctx) }

func (f feed) TableName() string { return f.feedDo.TableName() }

func (f feed) Alias() string { return f.feedDo.Alias() }

func (f feed) Columns(cols ...field.Expr) gen.Columns { return f.feedDo.Columns(cols...) }

func (f *feed) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *feed) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 1)
	f.fieldMap["id"] = f.ID
}

func (f feed) clone(db *gorm.DB) feed {
	f.feedDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f feed) replaceDB(db *gorm.DB) feed {
	f.feedDo.ReplaceDB(db)
	return f
}

type feedDo struct{ gen.DO }

func (f feedDo) Debug() *feedDo {
	return f.withDO(f.DO.Debug())
}

func (f feedDo) WithContext(ctx context.Context) *feedDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f feedDo) ReadDB() *feedDo {
	return f.Clauses(dbresolver.Read)
}

func (f feedDo) WriteDB() *feedDo {
	return f.Clauses(dbresolver.Write)
}

func (f feedDo) Session(config *gorm.Session) *feedDo {
	return f.withDO(f.DO.Session(config))
}

func (f feedDo) Clauses(conds ...clause.Expression) *feedDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f feedDo) Returning(value interface{}, columns ...string) *feedDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f feedDo) Not(conds ...gen.Condition) *feedDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f feedDo) Or(conds ...gen.Condition) *feedDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f feedDo) Select(conds ...field.Expr) *feedDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f feedDo) Where(conds ...gen.Condition) *feedDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f feedDo) Order(conds ...field.Expr) *feedDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f feedDo) Distinct(cols ...field.Expr) *feedDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f feedDo) Omit(cols ...field.Expr) *feedDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f feedDo) Join(table schema.Tabler, on ...field.Expr) *feedDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f feedDo) LeftJoin(table schema.Tabler, on ...field.Expr) *feedDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f feedDo) RightJoin(table schema.Tabler, on ...field.Expr) *feedDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f feedDo) Group(cols ...field.Expr) *feedDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f feedDo) Having(conds ...gen.Condition) *feedDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f feedDo) Limit(limit int) *feedDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f feedDo) Offset(offset int) *feedDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f feedDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *feedDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f feedDo) Unscoped() *feedDo {
	return f.withDO(f.DO.Unscoped())
}

func (f feedDo) Create(values ...*model.Feed) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f feedDo) CreateInBatches(values []*model.Feed, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f feedDo) Save(values ...*model.Feed) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f feedDo) First() (*model.Feed, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Feed), nil
	}
}

func (f feedDo) Take() (*model.Feed, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Feed), nil
	}
}

func (f feedDo) Last() (*model.Feed, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Feed), nil
	}
}

func (f feedDo) Find() ([]*model.Feed, error) {
	result, err := f.DO.Find()
	return result.([]*model.Feed), err
}

func (f feedDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Feed, err error) {
	buf := make([]*model.Feed, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f feedDo) FindInBatches(result *[]*model.Feed, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f feedDo) Attrs(attrs ...field.AssignExpr) *feedDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f feedDo) Assign(attrs ...field.AssignExpr) *feedDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f feedDo) Joins(fields ...field.RelationField) *feedDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f feedDo) Preload(fields ...field.RelationField) *feedDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f feedDo) FirstOrInit() (*model.Feed, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Feed), nil
	}
}

func (f feedDo) FirstOrCreate() (*model.Feed, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Feed), nil
	}
}

func (f feedDo) FindByPage(offset int, limit int) (result []*model.Feed, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f feedDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f feedDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f feedDo) Delete(models ...*model.Feed) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *feedDo) withDO(do gen.Dao) *feedDo {
	f.DO = *do.(*gen.DO)
	return f
}
