version: "3.8"

name: tophub

services:
  ### cli ################################################
  #  cli:
  #    container_name: cli

  ### server #############################################
  server:
    depends_on:
      - mysql
    build:
      context: ../../
      dockerfile: deploy/build/dockerfile-server
    container_name: tophub_server
    hostname: tophub_server
    networks:
      - mynet
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure

  ### MySQL ##############################################
  mysql:
    image: mysql:8.0.34
    container_name: tophub_mysql
    hostname: tophub_mysql
    networks:
      - mynet
    ports:
      - 33306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_PASSWORD:-default}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}
    volumes:
      - mysql:/var/lib/mysql
      - ../build/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql:
    driver: local

networks:
  mynet:
    driver: bridge