version: "3.8"

name: tophub

services:
  ### client #############################################
  client:
    depends_on:
      - server
    build:
      context: ../../
      dockerfile: deploy/build/dockerfile-client
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - COPY_CLIENT=${COPY_CLIENT}
    container_name: tophub_client
    hostname: tophub_client
    networks:
      - mynet
    ports:
      - 3000:80
    volumes:
      - ../build/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  ### cli ################################################
  cli:
    depends_on:
      - mysql
    build:
      context: ../../
      dockerfile: deploy/build/dockerfile-cli
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    container_name: tophub_cli
    hostname: tophub_cli
    networks:
      - mynet
    command: [ "crond", "-f" ]

  ### server #############################################
  server:
    depends_on:
      - mysql
    build:
      context: ../../
      dockerfile: deploy/build/dockerfile-server
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
    container_name: tophub_server
    hostname: tophub_server
    networks:
      - mynet
  server.debug:
    depends_on:
      - mysql
    build:
      context: ../../
      dockerfile: deploy/build/dockerfile-server.debug
    container_name: tophub_server.debug
    hostname: tophub_server.debug
    ports:
      - "40000:40000"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - mynet

  ### MySQL ##############################################
  mysql:
    image: mysql:8.0.34
    container_name: tophub_mysql
    hostname: tophub_mysql
    networks:
      - mynet
    ports:
      - 33306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-root}
      - MYSQL_USER=${MYSQL_PASSWORD:-default}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}
    volumes:
      - mysql:/var/lib/mysql
      - ../build/mysql/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql:
    driver: local

networks:
  mynet:
    driver: bridge